//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.drools.org/WS-HT", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.drools.ws_ht;
