//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//


package org.drools.ws_ht;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tDelegation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDelegation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="from" type="{http://www.drools.org/WS-HT}tFrom" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="potentialDelegatees" use="required" type="{http://www.drools.org/WS-HT}tPotentialDelegatees" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDelegation", propOrder = {
    "from"
})
@Entity(name = "org.drools.ws_ht.TDelegation")
@Table(name = "TDELEGATION")
public class TDelegation
    extends TExtensibleElements
    implements Equals, HashCode
{

    protected org.drools.ws_ht.TFrom from;
    @XmlAttribute(required = true)
    protected TPotentialDelegatees potentialDelegatees;

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TFrom }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TFrom.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "FROM__TDELEGATION_ID")
    public org.drools.ws_ht.TFrom getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TFrom }
     *     
     */
    public void setFrom(org.drools.ws_ht.TFrom value) {
        this.from = value;
    }

    /**
     * Gets the value of the potentialDelegatees property.
     * 
     * @return
     *     possible object is
     *     {@link TPotentialDelegatees }
     *     
     */
    @Basic
    @Column(name = "POTENTIALDELEGATEES")
    @Enumerated(EnumType.STRING)
    public TPotentialDelegatees getPotentialDelegatees() {
        return potentialDelegatees;
    }

    /**
     * Sets the value of the potentialDelegatees property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPotentialDelegatees }
     *     
     */
    public void setPotentialDelegatees(TPotentialDelegatees value) {
        this.potentialDelegatees = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TDelegation)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TDelegation that = ((TDelegation) object);
        equalsBuilder.append(this.getFrom(), that.getFrom());
        equalsBuilder.append(this.getPotentialDelegatees(), that.getPotentialDelegatees());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TDelegation)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getFrom());
        hashCodeBuilder.append(this.getPotentialDelegatees());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
