//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//


package org.drools.ws_ht;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tHumanInteractions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tHumanInteractions">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="extensions" type="{http://www.drools.org/WS-HT}tExtensions" minOccurs="0"/>
 *         &lt;element name="import" type="{http://www.drools.org/WS-HT}tImport" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}logicalPeopleGroups" minOccurs="0"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}tasks" minOccurs="0"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}notifications" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="targetNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="queryLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="expressionLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tHumanInteractions", propOrder = {
    "extensions",
    "_import",
    "logicalPeopleGroups",
    "tasks",
    "notifications"
})
@Entity(name = "org.drools.ws_ht.THumanInteractions")
@Table(name = "THUMANINTERACTIONS")
public class THumanInteractions
    extends TExtensibleElements
    implements Equals, HashCode
{

    protected org.drools.ws_ht.TExtensions extensions;
    @XmlElement(name = "import")
    protected List<org.drools.ws_ht.TImport> _import;
    protected org.drools.ws_ht.TLogicalPeopleGroups logicalPeopleGroups;
    protected org.drools.ws_ht.TTasks tasks;
    protected org.drools.ws_ht.TNotifications notifications;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String targetNamespace;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String queryLanguage;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String expressionLanguage;

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TExtensions }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TExtensions.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "EXTENSIONS_THUMANINTERACTION_0")
    public org.drools.ws_ht.TExtensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TExtensions }
     *     
     */
    public void setExtensions(org.drools.ws_ht.TExtensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the import property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the import property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.ws_ht.TImport }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.ws_ht.TImport.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "IMPORT_THUMANINTERACTIONS_ID")
    public List<org.drools.ws_ht.TImport> getImport() {
        if (_import == null) {
            _import = new ArrayList<org.drools.ws_ht.TImport>();
        }
        return this._import;
    }

    /**
     * 
     * 
     */
    public void setImport(List<org.drools.ws_ht.TImport> _import) {
        this._import = _import;
    }

    /**
     * Gets the value of the logicalPeopleGroups property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TLogicalPeopleGroups }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TLogicalPeopleGroups.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "LOGICALPEOPLEGROUPS_THUMANIN_0")
    public org.drools.ws_ht.TLogicalPeopleGroups getLogicalPeopleGroups() {
        return logicalPeopleGroups;
    }

    /**
     * Sets the value of the logicalPeopleGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TLogicalPeopleGroups }
     *     
     */
    public void setLogicalPeopleGroups(org.drools.ws_ht.TLogicalPeopleGroups value) {
        this.logicalPeopleGroups = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TTasks }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TTasks.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TASKS_THUMANINTERACTIONS_ID")
    public org.drools.ws_ht.TTasks getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TTasks }
     *     
     */
    public void setTasks(org.drools.ws_ht.TTasks value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the notifications property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TNotifications }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TNotifications.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "NOTIFICATIONS_THUMANINTERACT_0")
    public org.drools.ws_ht.TNotifications getNotifications() {
        return notifications;
    }

    /**
     * Sets the value of the notifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TNotifications }
     *     
     */
    public void setNotifications(org.drools.ws_ht.TNotifications value) {
        this.notifications = value;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TARGETNAMESPACE")
    public String getTargetNamespace() {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }

    /**
     * Gets the value of the queryLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "QUERYLANGUAGE")
    public String getQueryLanguage() {
        return queryLanguage;
    }

    /**
     * Sets the value of the queryLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryLanguage(String value) {
        this.queryLanguage = value;
    }

    /**
     * Gets the value of the expressionLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EXPRESSIONLANGUAGE")
    public String getExpressionLanguage() {
        return expressionLanguage;
    }

    /**
     * Sets the value of the expressionLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpressionLanguage(String value) {
        this.expressionLanguage = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof THumanInteractions)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final THumanInteractions that = ((THumanInteractions) object);
        equalsBuilder.append(this.getExtensions(), that.getExtensions());
        equalsBuilder.append(this.getImport(), that.getImport());
        equalsBuilder.append(this.getLogicalPeopleGroups(), that.getLogicalPeopleGroups());
        equalsBuilder.append(this.getTasks(), that.getTasks());
        equalsBuilder.append(this.getNotifications(), that.getNotifications());
        equalsBuilder.append(this.getTargetNamespace(), that.getTargetNamespace());
        equalsBuilder.append(this.getQueryLanguage(), that.getQueryLanguage());
        equalsBuilder.append(this.getExpressionLanguage(), that.getExpressionLanguage());
    }

    public boolean equals(Object object) {
        if (!(object instanceof THumanInteractions)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getExtensions());
        hashCodeBuilder.append(this.getImport());
        hashCodeBuilder.append(this.getLogicalPeopleGroups());
        hashCodeBuilder.append(this.getTasks());
        hashCodeBuilder.append(this.getNotifications());
        hashCodeBuilder.append(this.getTargetNamespace());
        hashCodeBuilder.append(this.getQueryLanguage());
        hashCodeBuilder.append(this.getExpressionLanguage());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
