//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//


package org.drools.ws_ht;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tLogicalPeopleGroups complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tLogicalPeopleGroups">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="logicalPeopleGroup" type="{http://www.drools.org/WS-HT}tLogicalPeopleGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLogicalPeopleGroups", propOrder = {
    "logicalPeopleGroup"
})
@Entity(name = "org.drools.ws_ht.TLogicalPeopleGroups")
@Table(name = "TLOGICALPEOPLEGROUPS")
public class TLogicalPeopleGroups
    extends TExtensibleElements
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected List<org.drools.ws_ht.TLogicalPeopleGroup> logicalPeopleGroup;

    /**
     * Gets the value of the logicalPeopleGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logicalPeopleGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogicalPeopleGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.ws_ht.TLogicalPeopleGroup }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.ws_ht.TLogicalPeopleGroup.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "LOGICALPEOPLEGROUP_TLOGICALP_0")
    public List<org.drools.ws_ht.TLogicalPeopleGroup> getLogicalPeopleGroup() {
        if (logicalPeopleGroup == null) {
            logicalPeopleGroup = new ArrayList<org.drools.ws_ht.TLogicalPeopleGroup>();
        }
        return this.logicalPeopleGroup;
    }

    /**
     * 
     * 
     */
    public void setLogicalPeopleGroup(List<org.drools.ws_ht.TLogicalPeopleGroup> logicalPeopleGroup) {
        this.logicalPeopleGroup = logicalPeopleGroup;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TLogicalPeopleGroups)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TLogicalPeopleGroups that = ((TLogicalPeopleGroups) object);
        equalsBuilder.append(this.getLogicalPeopleGroup(), that.getLogicalPeopleGroup());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TLogicalPeopleGroups)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getLogicalPeopleGroup());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
