//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//


package org.drools.ws_ht;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tNotification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="interface" type="{http://www.drools.org/WS-HT}tNotificationInterface"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}priority" minOccurs="0"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}peopleAssignments"/>
 *         &lt;element name="presentationElements" type="{http://www.drools.org/WS-HT}tPresentationElements"/>
 *         &lt;element name="renderings" type="{http://www.drools.org/WS-HT}tRenderings" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tNotification", propOrder = {
    "_interface",
    "priority",
    "peopleAssignments",
    "presentationElements",
    "renderings"
})
@Entity(name = "org.drools.ws_ht.TNotification")
@Table(name = "TNOTIFICATION")
public class TNotification
    extends TExtensibleElements
    implements Equals, HashCode
{

    @XmlElement(name = "interface", required = true)
    protected org.drools.ws_ht.TNotificationInterface _interface;
    protected org.drools.ws_ht.TPriority priority;
    @XmlElement(required = true)
    protected org.drools.ws_ht.TPeopleAssignments peopleAssignments;
    @XmlElement(required = true)
    protected org.drools.ws_ht.TPresentationElements presentationElements;
    protected org.drools.ws_ht.TRenderings renderings;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TNotificationInterface }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TNotificationInterface.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INTERFACE_TNOTIFICATION_ID")
    public org.drools.ws_ht.TNotificationInterface getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TNotificationInterface }
     *     
     */
    public void setInterface(org.drools.ws_ht.TNotificationInterface value) {
        this._interface = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TPriority }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TPriority.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRIORITY_TNOTIFICATION_ID")
    public org.drools.ws_ht.TPriority getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TPriority }
     *     
     */
    public void setPriority(org.drools.ws_ht.TPriority value) {
        this.priority = value;
    }

    /**
     * Gets the value of the peopleAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TPeopleAssignments }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TPeopleAssignments.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PEOPLEASSIGNMENTS_TNOTIFICAT_0")
    public org.drools.ws_ht.TPeopleAssignments getPeopleAssignments() {
        return peopleAssignments;
    }

    /**
     * Sets the value of the peopleAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TPeopleAssignments }
     *     
     */
    public void setPeopleAssignments(org.drools.ws_ht.TPeopleAssignments value) {
        this.peopleAssignments = value;
    }

    /**
     * Gets the value of the presentationElements property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TPresentationElements }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TPresentationElements.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRESENTATIONELEMENTS_TNOTIFI_0")
    public org.drools.ws_ht.TPresentationElements getPresentationElements() {
        return presentationElements;
    }

    /**
     * Sets the value of the presentationElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TPresentationElements }
     *     
     */
    public void setPresentationElements(org.drools.ws_ht.TPresentationElements value) {
        this.presentationElements = value;
    }

    /**
     * Gets the value of the renderings property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TRenderings }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TRenderings.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RENDERINGS_TNOTIFICATION_ID")
    public org.drools.ws_ht.TRenderings getRenderings() {
        return renderings;
    }

    /**
     * Sets the value of the renderings property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TRenderings }
     *     
     */
    public void setRenderings(org.drools.ws_ht.TRenderings value) {
        this.renderings = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAME_")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TNotification)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TNotification that = ((TNotification) object);
        equalsBuilder.append(this.getInterface(), that.getInterface());
        equalsBuilder.append(this.getPriority(), that.getPriority());
        equalsBuilder.append(this.getPeopleAssignments(), that.getPeopleAssignments());
        equalsBuilder.append(this.getPresentationElements(), that.getPresentationElements());
        equalsBuilder.append(this.getRenderings(), that.getRenderings());
        equalsBuilder.append(this.getName(), that.getName());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TNotification)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getInterface());
        hashCodeBuilder.append(this.getPriority());
        hashCodeBuilder.append(this.getPeopleAssignments());
        hashCodeBuilder.append(this.getPresentationElements());
        hashCodeBuilder.append(this.getRenderings());
        hashCodeBuilder.append(this.getName());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
