//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//


package org.drools.ws_ht.api.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="taskAbstract" type="{http://www.drools.org/WS-HT/api}tTaskAbstract" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taskAbstract"
})
@XmlRootElement(name = "getMyTaskAbstractsResponse")
@Entity(name = "org.drools.ws_ht.api.xsd.GetMyTaskAbstractsResponse")
@Table(name = "GETMYTASKABSTRACTSRESPONSE")
@Inheritance(strategy = InheritanceType.JOINED)
public class GetMyTaskAbstractsResponse
    implements Equals, HashCode
{

    protected List<org.drools.ws_ht.api.TTaskAbstract> taskAbstract;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the taskAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.ws_ht.api.TTaskAbstract }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.ws_ht.api.TTaskAbstract.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TASKABSTRACT_GETMYTASKABSTRA_0")
    public List<org.drools.ws_ht.api.TTaskAbstract> getTaskAbstract() {
        if (taskAbstract == null) {
            taskAbstract = new ArrayList<org.drools.ws_ht.api.TTaskAbstract>();
        }
        return this.taskAbstract;
    }

    /**
     * 
     * 
     */
    public void setTaskAbstract(List<org.drools.ws_ht.api.TTaskAbstract> taskAbstract) {
        this.taskAbstract = taskAbstract;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof GetMyTaskAbstractsResponse)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final GetMyTaskAbstractsResponse that = ((GetMyTaskAbstractsResponse) object);
        equalsBuilder.append(this.getTaskAbstract(), that.getTaskAbstract());
    }

    public boolean equals(Object object) {
        if (!(object instanceof GetMyTaskAbstractsResponse)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getTaskAbstract());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
