//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tDeadline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDeadline">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="for" type="{http://www.example.org/WS-HT}tDuration-expr"/>
 *           &lt;element name="until" type="{http://www.example.org/WS-HT}tDeadline-expr"/>
 *         &lt;/choice>
 *         &lt;element name="escalation" type="{http://www.example.org/WS-HT}tEscalation" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDeadline", propOrder = {
    "_for",
    "until",
    "escalation"
})
@Entity(name = "org.example.ws_ht.TDeadline")
@Table(name = "TDEADLINE")
public class TDeadline
    extends TExtensibleElements
    implements Equals, HashCode
{

    @XmlElement(name = "for")
    protected org.drools.task.TDurationExpr _for;
    protected org.drools.task.TDeadlineExpr until;
    protected List<org.drools.task.TEscalation> escalation;

    /**
     * Gets the value of the for property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TDurationExpr }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TDurationExpr.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "FOR__TDEADLINE_ID")
    public org.drools.task.TDurationExpr getFor() {
        return _for;
    }

    /**
     * Sets the value of the for property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TDurationExpr }
     *     
     */
    public void setFor(org.drools.task.TDurationExpr value) {
        this._for = value;
    }

    /**
     * Gets the value of the until property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TDeadlineExpr }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TDeadlineExpr.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "UNTIL__TDEADLINE_ID")
    public org.drools.task.TDeadlineExpr getUntil() {
        return until;
    }

    /**
     * Sets the value of the until property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TDeadlineExpr }
     *     
     */
    public void setUntil(org.drools.task.TDeadlineExpr value) {
        this.until = value;
    }

    /**
     * Gets the value of the escalation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the escalation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEscalation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TEscalation }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TEscalation.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ESCALATION_TDEADLINE_ID")
    public List<org.drools.task.TEscalation> getEscalation() {
        if (escalation == null) {
            escalation = new ArrayList<org.drools.task.TEscalation>();
        }
        return this.escalation;
    }

    /**
     * 
     * 
     */
    public void setEscalation(List<org.drools.task.TEscalation> escalation) {
        this.escalation = escalation;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TDeadline)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TDeadline that = ((TDeadline) object);
        equalsBuilder.append(this.getFor(), that.getFor());
        equalsBuilder.append(this.getUntil(), that.getUntil());
        equalsBuilder.append(this.getEscalation(), that.getEscalation());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TDeadline)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getFor());
        hashCodeBuilder.append(this.getUntil());
        hashCodeBuilder.append(this.getEscalation());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
