//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tEscalation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tEscalation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://www.drools.org/WS-HT}tBoolean-expr" minOccurs="0"/>
 *         &lt;element name="toParts" type="{http://www.drools.org/WS-HT}tToParts" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.drools.org/WS-HT}notification"/>
 *           &lt;element name="localNotification" type="{http://www.drools.org/WS-HT}tLocalNotification"/>
 *           &lt;element name="reassignment" type="{http://www.drools.org/WS-HT}tReassignment"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tEscalation", propOrder = {
    "condition",
    "toParts",
    "notification",
    "localNotification",
    "reassignment"
})
@Entity(name = "org.drools.task.TEscalation")
@Table(name = "TESCALATION")
public class TEscalation
    extends TExtensibleElements
    implements Equals, HashCode
{

    protected org.drools.task.TBooleanExpr condition;
    protected List<org.drools.task.TToParts> toParts;
    protected org.drools.task.TNotification notification;
    protected org.drools.task.TLocalNotification localNotification;
    protected org.drools.task.TReassignment reassignment;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TBooleanExpr }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TBooleanExpr.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CONDITION_TESCALATION_ID")
    public org.drools.task.TBooleanExpr getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TBooleanExpr }
     *     
     */
    public void setCondition(org.drools.task.TBooleanExpr value) {
        this.condition = value;
    }

    /**
     * Gets the value of the toParts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toParts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToParts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TToParts }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TToParts.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TOPARTS_TESCALATION_ID")
    public List<org.drools.task.TToParts> getToParts() {
        if (toParts == null) {
            toParts = new ArrayList<org.drools.task.TToParts>();
        }
        return this.toParts;
    }

    /**
     * 
     * 
     */
    public void setToParts(List<org.drools.task.TToParts> toParts) {
        this.toParts = toParts;
    }

    /**
     * Gets the value of the notification property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TNotification }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TNotification.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "NOTIFICATION_TESCALATION_ID")
    public org.drools.task.TNotification getNotification() {
        return notification;
    }

    /**
     * Sets the value of the notification property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TNotification }
     *     
     */
    public void setNotification(org.drools.task.TNotification value) {
        this.notification = value;
    }

    /**
     * Gets the value of the localNotification property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TLocalNotification }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TLocalNotification.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "LOCALNOTIFICATION_TESCALATIO_0")
    public org.drools.task.TLocalNotification getLocalNotification() {
        return localNotification;
    }

    /**
     * Sets the value of the localNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TLocalNotification }
     *     
     */
    public void setLocalNotification(org.drools.task.TLocalNotification value) {
        this.localNotification = value;
    }

    /**
     * Gets the value of the reassignment property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TReassignment }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TReassignment.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "REASSIGNMENT_TESCALATION_ID")
    public org.drools.task.TReassignment getReassignment() {
        return reassignment;
    }

    /**
     * Sets the value of the reassignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TReassignment }
     *     
     */
    public void setReassignment(org.drools.task.TReassignment value) {
        this.reassignment = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAME_")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TEscalation)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TEscalation that = ((TEscalation) object);
        equalsBuilder.append(this.getCondition(), that.getCondition());
        equalsBuilder.append(this.getToParts(), that.getToParts());
        equalsBuilder.append(this.getNotification(), that.getNotification());
        equalsBuilder.append(this.getLocalNotification(), that.getLocalNotification());
        equalsBuilder.append(this.getReassignment(), that.getReassignment());
        equalsBuilder.append(this.getName(), that.getName());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TEscalation)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getCondition());
        hashCodeBuilder.append(this.getToParts());
        hashCodeBuilder.append(this.getNotification());
        hashCodeBuilder.append(this.getLocalNotification());
        hashCodeBuilder.append(this.getReassignment());
        hashCodeBuilder.append(this.getName());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
