//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.QNameAsString;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tLocalNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tLocalNotification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/WS-HT}tExtensibleElements">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.example.org/WS-HT}priority" minOccurs="0"/>
 *           &lt;element ref="{http://www.example.org/WS-HT}peopleAssignments" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute name="reference" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tLocalNotification", propOrder = {
    "priority",
    "peopleAssignments"
})
@Entity(name = "org.example.ws_ht.TLocalNotification")
@Table(name = "TLOCALNOTIFICATION")
public class TLocalNotification
    extends TExtensibleElements
    implements Equals, HashCode
{

    protected org.drools.task.TPriority priority;
    protected org.drools.task.TPeopleAssignments peopleAssignments;
    @XmlAttribute(required = true)
    protected QName reference;

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TPriority }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TPriority.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRIORITY_TLOCALNOTIFICATION__0")
    public org.drools.task.TPriority getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TPriority }
     *     
     */
    public void setPriority(org.drools.task.TPriority value) {
        this.priority = value;
    }

    /**
     * Gets the value of the peopleAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TPeopleAssignments }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TPeopleAssignments.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PEOPLEASSIGNMENTS_TLOCALNOTI_0")
    public org.drools.task.TPeopleAssignments getPeopleAssignments() {
        return peopleAssignments;
    }

    /**
     * Sets the value of the peopleAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TPeopleAssignments }
     *     
     */
    public void setPeopleAssignments(org.drools.task.TPeopleAssignments value) {
        this.peopleAssignments = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    @Transient
    public QName getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setReference(QName value) {
        this.reference = value;
    }

    @Basic
    @Column(name = "REFERENCEITEM")
    public String getReferenceItem() {
        return XmlAdapterUtils.unmarshall(QNameAsString.class, this.getReference());
    }

    public void setReferenceItem(String target) {
        setReference(XmlAdapterUtils.marshall(QNameAsString.class, target));
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TLocalNotification)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TLocalNotification that = ((TLocalNotification) object);
        equalsBuilder.append(this.getPriority(), that.getPriority());
        equalsBuilder.append(this.getPeopleAssignments(), that.getPeopleAssignments());
        equalsBuilder.append(this.getReference(), that.getReference());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TLocalNotification)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getPriority());
        hashCodeBuilder.append(this.getPeopleAssignments());
        hashCodeBuilder.append(this.getReference());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
