//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tOrganizationalEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOrganizationalEntity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.example.org/WS-HT}users"/>
 *         &lt;element ref="{http://www.example.org/WS-HT}groups"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOrganizationalEntity", propOrder = {
    "users",
    "groups"
})
@Entity(name = "org.example.ws_ht.TOrganizationalEntity")
@Table(name = "TORGANIZATIONALENTITY")
@Inheritance(strategy = InheritanceType.JOINED)
public class TOrganizationalEntity
    implements Equals, HashCode
{

    protected org.drools.task.TUserlist users;
    protected org.drools.task.TGrouplist groups;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TUserlist }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TUserlist.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "USERS_TORGANIZATIONALENTITY__0")
    public org.drools.task.TUserlist getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TUserlist }
     *     
     */
    public void setUsers(org.drools.task.TUserlist value) {
        this.users = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TGrouplist }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TGrouplist.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "GROUPS_TORGANIZATIONALENTITY_0")
    public org.drools.task.TGrouplist getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TGrouplist }
     *     
     */
    public void setGroups(org.drools.task.TGrouplist value) {
        this.groups = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TOrganizationalEntity)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final TOrganizationalEntity that = ((TOrganizationalEntity) object);
        equalsBuilder.append(this.getUsers(), that.getUsers());
        equalsBuilder.append(this.getGroups(), that.getGroups());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TOrganizationalEntity)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getUsers());
        hashCodeBuilder.append(this.getGroups());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
