//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tPresentationElements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPresentationElements">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.example.org/WS-HT}tText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="presentationParameters" type="{http://www.example.org/WS-HT}tPresentationParameters" minOccurs="0"/>
 *         &lt;element name="subject" type="{http://www.example.org/WS-HT}tText" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.example.org/WS-HT}tDescription" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPresentationElements", propOrder = {
    "name",
    "presentationParameters",
    "subject",
    "description"
})
@Entity(name = "org.example.ws_ht.TPresentationElements")
@Table(name = "TPRESENTATIONELEMENTS")
public class TPresentationElements
    extends TExtensibleElements
    implements Equals, HashCode
{

    protected List<org.drools.task.TText> name;
    protected org.drools.task.TPresentationParameters presentationParameters;
    protected List<org.drools.task.TText> subject;
    protected List<org.drools.task.TDescription> description;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TText }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TText.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "NAME__TPRESENTATIONELEMENTS__0")
    public List<org.drools.task.TText> getName() {
        if (name == null) {
            name = new ArrayList<org.drools.task.TText>();
        }
        return this.name;
    }

    /**
     * 
     * 
     */
    public void setName(List<org.drools.task.TText> name) {
        this.name = name;
    }

    /**
     * Gets the value of the presentationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TPresentationParameters }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TPresentationParameters.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRESENTATIONPARAMETERS_TPRES_0")
    public org.drools.task.TPresentationParameters getPresentationParameters() {
        return presentationParameters;
    }

    /**
     * Sets the value of the presentationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TPresentationParameters }
     *     
     */
    public void setPresentationParameters(org.drools.task.TPresentationParameters value) {
        this.presentationParameters = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TText }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TText.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SUBJECT_TPRESENTATIONELEMENT_0")
    public List<org.drools.task.TText> getSubject() {
        if (subject == null) {
            subject = new ArrayList<org.drools.task.TText>();
        }
        return this.subject;
    }

    /**
     * 
     * 
     */
    public void setSubject(List<org.drools.task.TText> subject) {
        this.subject = subject;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TDescription }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TDescription.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DESCRIPTION_TPRESENTATIONELE_0")
    public List<org.drools.task.TDescription> getDescription() {
        if (description == null) {
            description = new ArrayList<org.drools.task.TDescription>();
        }
        return this.description;
    }

    /**
     * 
     * 
     */
    public void setDescription(List<org.drools.task.TDescription> description) {
        this.description = description;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TPresentationElements)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TPresentationElements that = ((TPresentationElements) object);
        equalsBuilder.append(this.getName(), that.getName());
        equalsBuilder.append(this.getPresentationParameters(), that.getPresentationParameters());
        equalsBuilder.append(this.getSubject(), that.getSubject());
        equalsBuilder.append(this.getDescription(), that.getDescription());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TPresentationElements)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getName());
        hashCodeBuilder.append(this.getPresentationParameters());
        hashCodeBuilder.append(this.getSubject());
        hashCodeBuilder.append(this.getDescription());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
