//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tPresentationParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tPresentationParameters">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="presentationParameter" type="{http://www.drools.org/WS-HT}tPresentationParameter" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="expressionLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPresentationParameters", propOrder = {
    "presentationParameter"
})
@Entity(name = "org.drools.task.TPresentationParameters")
@Table(name = "TPRESENTATIONPARAMETERS")
public class TPresentationParameters
    extends TExtensibleElements
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected List<org.drools.task.TPresentationParameter> presentationParameter;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String expressionLanguage;

    /**
     * Gets the value of the presentationParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentationParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentationParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TPresentationParameter }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TPresentationParameter.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRESENTATIONPARAMETER_TPRESE_0")
    public List<org.drools.task.TPresentationParameter> getPresentationParameter() {
        if (presentationParameter == null) {
            presentationParameter = new ArrayList<org.drools.task.TPresentationParameter>();
        }
        return this.presentationParameter;
    }

    /**
     * 
     * 
     */
    public void setPresentationParameter(List<org.drools.task.TPresentationParameter> presentationParameter) {
        this.presentationParameter = presentationParameter;
    }

    /**
     * Gets the value of the expressionLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EXPRESSIONLANGUAGE")
    public String getExpressionLanguage() {
        return expressionLanguage;
    }

    /**
     * Sets the value of the expressionLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpressionLanguage(String value) {
        this.expressionLanguage = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TPresentationParameters)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TPresentationParameters that = ((TPresentationParameters) object);
        equalsBuilder.append(this.getPresentationParameter(), that.getPresentationParameter());
        equalsBuilder.append(this.getExpressionLanguage(), that.getExpressionLanguage());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TPresentationParameters)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getPresentationParameter());
        hashCodeBuilder.append(this.getExpressionLanguage());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
