//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tTask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTask">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="interface" type="{http://www.drools.org/WS-HT}tTaskInterface"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}priority" minOccurs="0"/>
 *         &lt;element ref="{http://www.drools.org/WS-HT}peopleAssignments"/>
 *         &lt;element name="delegation" type="{http://www.drools.org/WS-HT}tDelegation" minOccurs="0"/>
 *         &lt;element name="presentationElements" type="{http://www.drools.org/WS-HT}tPresentationElements"/>
 *         &lt;element name="outcome" type="{http://www.drools.org/WS-HT}tQuery" minOccurs="0"/>
 *         &lt;element name="searchBy" type="{http://www.drools.org/WS-HT}tExpression" minOccurs="0"/>
 *         &lt;element name="renderings" type="{http://www.drools.org/WS-HT}tRenderings" minOccurs="0"/>
 *         &lt;element name="deadlines" type="{http://www.drools.org/WS-HT}tDeadlines" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTask", propOrder = {
    "_interface",
    "priority",
    "peopleAssignments",
    "delegation",
    "presentationElements",
    "outcome",
    "searchBy",
    "renderings",
    "deadlines"
})
@Entity(name = "org.drools.task.TTask")
@Table(name = "TTASK")
public class TTask
    extends TExtensibleElements
    implements Equals, HashCode
{

    @XmlElement(name = "interface", required = true)
    protected org.drools.task.TTaskInterface _interface;
    protected org.drools.task.TPriority priority;
    @XmlElement(required = true)
    protected org.drools.task.TPeopleAssignments peopleAssignments;
    protected org.drools.task.TDelegation delegation;
    @XmlElement(required = true)
    protected org.drools.task.TPresentationElements presentationElements;
    protected org.drools.task.TQuery outcome;
    protected org.drools.task.TExpression searchBy;
    protected org.drools.task.TRenderings renderings;
    protected org.drools.task.TDeadlines deadlines;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the interface property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TTaskInterface }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TTaskInterface.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INTERFACE_TTASK_ID")
    public org.drools.task.TTaskInterface getInterface() {
        return _interface;
    }

    /**
     * Sets the value of the interface property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TTaskInterface }
     *     
     */
    public void setInterface(org.drools.task.TTaskInterface value) {
        this._interface = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TPriority }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TPriority.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRIORITY_TTASK_ID")
    public org.drools.task.TPriority getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TPriority }
     *     
     */
    public void setPriority(org.drools.task.TPriority value) {
        this.priority = value;
    }

    /**
     * Gets the value of the peopleAssignments property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TPeopleAssignments }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TPeopleAssignments.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PEOPLEASSIGNMENTS_TTASK_ID")
    public org.drools.task.TPeopleAssignments getPeopleAssignments() {
        return peopleAssignments;
    }

    /**
     * Sets the value of the peopleAssignments property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TPeopleAssignments }
     *     
     */
    public void setPeopleAssignments(org.drools.task.TPeopleAssignments value) {
        this.peopleAssignments = value;
    }

    /**
     * Gets the value of the delegation property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TDelegation }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TDelegation.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DELEGATION_TTASK_ID")
    public org.drools.task.TDelegation getDelegation() {
        return delegation;
    }

    /**
     * Sets the value of the delegation property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TDelegation }
     *     
     */
    public void setDelegation(org.drools.task.TDelegation value) {
        this.delegation = value;
    }

    /**
     * Gets the value of the presentationElements property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TPresentationElements }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TPresentationElements.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PRESENTATIONELEMENTS_TTASK_ID")
    public org.drools.task.TPresentationElements getPresentationElements() {
        return presentationElements;
    }

    /**
     * Sets the value of the presentationElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TPresentationElements }
     *     
     */
    public void setPresentationElements(org.drools.task.TPresentationElements value) {
        this.presentationElements = value;
    }

    /**
     * Gets the value of the outcome property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TQuery }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TQuery.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OUTCOME_TTASK_ID")
    public org.drools.task.TQuery getOutcome() {
        return outcome;
    }

    /**
     * Sets the value of the outcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TQuery }
     *     
     */
    public void setOutcome(org.drools.task.TQuery value) {
        this.outcome = value;
    }

    /**
     * Gets the value of the searchBy property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TExpression }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TExpression.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SEARCHBY_TTASK_ID")
    public org.drools.task.TExpression getSearchBy() {
        return searchBy;
    }

    /**
     * Sets the value of the searchBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TExpression }
     *     
     */
    public void setSearchBy(org.drools.task.TExpression value) {
        this.searchBy = value;
    }

    /**
     * Gets the value of the renderings property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TRenderings }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TRenderings.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RENDERINGS_TTASK_ID")
    public org.drools.task.TRenderings getRenderings() {
        return renderings;
    }

    /**
     * Sets the value of the renderings property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TRenderings }
     *     
     */
    public void setRenderings(org.drools.task.TRenderings value) {
        this.renderings = value;
    }

    /**
     * Gets the value of the deadlines property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.task.TDeadlines }
     *     
     */
    @ManyToOne(targetEntity = org.drools.task.TDeadlines.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DEADLINES_TTASK_ID")
    public org.drools.task.TDeadlines getDeadlines() {
        return deadlines;
    }

    /**
     * Sets the value of the deadlines property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.task.TDeadlines }
     *     
     */
    public void setDeadlines(org.drools.task.TDeadlines value) {
        this.deadlines = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAME_")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TTask)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TTask that = ((TTask) object);
        equalsBuilder.append(this.getInterface(), that.getInterface());
        equalsBuilder.append(this.getPriority(), that.getPriority());
        equalsBuilder.append(this.getPeopleAssignments(), that.getPeopleAssignments());
        equalsBuilder.append(this.getDelegation(), that.getDelegation());
        equalsBuilder.append(this.getPresentationElements(), that.getPresentationElements());
        equalsBuilder.append(this.getOutcome(), that.getOutcome());
        equalsBuilder.append(this.getSearchBy(), that.getSearchBy());
        equalsBuilder.append(this.getRenderings(), that.getRenderings());
        equalsBuilder.append(this.getDeadlines(), that.getDeadlines());
        equalsBuilder.append(this.getName(), that.getName());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TTask)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getInterface());
        hashCodeBuilder.append(this.getPriority());
        hashCodeBuilder.append(this.getPeopleAssignments());
        hashCodeBuilder.append(this.getDelegation());
        hashCodeBuilder.append(this.getPresentationElements());
        hashCodeBuilder.append(this.getOutcome());
        hashCodeBuilder.append(this.getSearchBy());
        hashCodeBuilder.append(this.getRenderings());
        hashCodeBuilder.append(this.getDeadlines());
        hashCodeBuilder.append(this.getName());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
