//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.19 at 11:36:25 PM BST 
//


package org.drools.task;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;


/**
 * <p>Java class for tToParts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tToParts">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.drools.org/WS-HT}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="toPart" type="{http://www.drools.org/WS-HT}tToPart" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tToParts", propOrder = {
    "toPart"
})
@Entity(name = "org.drools.task.TToParts")
@Table(name = "TTOPARTS")
public class TToParts
    extends TExtensibleElements
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected List<org.drools.task.TToPart> toPart;

    /**
     * Gets the value of the toPart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toPart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToPart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.drools.task.TToPart }
     * 
     * 
     */
    @OneToMany(targetEntity = org.drools.task.TToPart.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TOPART_TTOPARTS_ID")
    public List<org.drools.task.TToPart> getToPart() {
        if (toPart == null) {
            toPart = new ArrayList<org.drools.task.TToPart>();
        }
        return this.toPart;
    }

    /**
     * 
     * 
     */
    public void setToPart(List<org.drools.task.TToPart> toPart) {
        this.toPart = toPart;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TToParts)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TToParts that = ((TToParts) object);
        equalsBuilder.append(this.getToPart(), that.getToPart());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TToParts)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getToPart());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

}
