//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.21 at 05:31:46 AM BST 
//


package org.drools.ws_ht.api;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.hyperjaxb3.xml.bind.JAXBContextUtils;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.ElementAsString;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.QNameAsString;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.w3c.dom.Element;


/**
 * <p>Java class for tTask complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tTask">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="taskType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}QName"/>
 *         &lt;element name="status" type="{http://www.drools.org/WS-HT/api}tStatus"/>
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="taskInitiator" type="{http://www.drools.org/WS-HT}tUser" minOccurs="0"/>
 *         &lt;element name="taskStakeholders" type="{http://www.drools.org/WS-HT}tOrganizationalEntity" minOccurs="0"/>
 *         &lt;element name="potentialOwners" type="{http://www.drools.org/WS-HT}tOrganizationalEntity" minOccurs="0"/>
 *         &lt;element name="businessAdministrators" type="{http://www.drools.org/WS-HT}tOrganizationalEntity" minOccurs="0"/>
 *         &lt;element name="actualOwner" type="{http://www.drools.org/WS-HT}tUser" minOccurs="0"/>
 *         &lt;element name="notificationRecipients" type="{http://www.drools.org/WS-HT}tOrganizationalEntity" minOccurs="0"/>
 *         &lt;element name="createdOn" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="activationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="expirationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="isSkipable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasPotentialOwners" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="startByExists" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="completeByExists" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="presentationName" type="{http://www.drools.org/WS-HT/api}tPresentationName" minOccurs="0"/>
 *         &lt;element name="presentationSubject" type="{http://www.drools.org/WS-HT/api}tPresentationSubject" minOccurs="0"/>
 *         &lt;element name="renderingMethodExists" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasOutput" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasFault" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasAttachments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasComments" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="escalated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="primarySearchBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tTask", propOrder = {
    "id",
    "taskType",
    "name",
    "status",
    "priority",
    "taskInitiator",
    "taskStakeholders",
    "potentialOwners",
    "businessAdministrators",
    "actualOwner",
    "notificationRecipients",
    "createdOn",
    "createdBy",
    "activationTime",
    "expirationTime",
    "isSkipable",
    "hasPotentialOwners",
    "startByExists",
    "completeByExists",
    "presentationName",
    "presentationSubject",
    "renderingMethodExists",
    "hasOutput",
    "hasFault",
    "hasAttachments",
    "hasComments",
    "escalated",
    "primarySearchBy",
    "any"
})
@Entity(name = "org.drools.ws_ht.api.TTask")
@Table(name = "TTASK")
@Inheritance(strategy = InheritanceType.JOINED)
public class TTask
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String taskType;
    @XmlElement(required = true)
    protected QName name;
    @XmlElement(required = true)
    protected TStatus status;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger priority;
    protected String taskInitiator;
    protected org.drools.ws_ht.TOrganizationalEntity taskStakeholders;
    protected org.drools.ws_ht.TOrganizationalEntity potentialOwners;
    protected org.drools.ws_ht.TOrganizationalEntity businessAdministrators;
    protected String actualOwner;
    protected org.drools.ws_ht.TOrganizationalEntity notificationRecipients;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdOn;
    protected String createdBy;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activationTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationTime;
    protected Boolean isSkipable;
    protected Boolean hasPotentialOwners;
    protected Boolean startByExists;
    protected Boolean completeByExists;
    protected String presentationName;
    protected String presentationSubject;
    protected boolean renderingMethodExists;
    protected Boolean hasOutput;
    protected Boolean hasFault;
    protected Boolean hasAttachments;
    protected Boolean hasComments;
    protected Boolean escalated;
    protected String primarySearchBy;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    @XmlTransient
    protected List<TTask.AnyItem> anyItems;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ID")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the taskType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TASKTYPE")
    public String getTaskType() {
        return taskType;
    }

    /**
     * Sets the value of the taskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskType(String value) {
        this.taskType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    @Transient
    public QName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setName(QName value) {
        this.name = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link TStatus }
     *     
     */
    @Basic
    @Column(name = "STATUS")
    @Enumerated(EnumType.STRING)
    public TStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStatus }
     *     
     */
    public void setStatus(TStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "PRIORITY", scale = 0)
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the taskInitiator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TASKINITIATOR")
    public String getTaskInitiator() {
        return taskInitiator;
    }

    /**
     * Sets the value of the taskInitiator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskInitiator(String value) {
        this.taskInitiator = value;
    }

    /**
     * Gets the value of the taskStakeholders property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TOrganizationalEntity.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TASKSTAKEHOLDERS_TTASK_ID")
    public org.drools.ws_ht.TOrganizationalEntity getTaskStakeholders() {
        return taskStakeholders;
    }

    /**
     * Sets the value of the taskStakeholders property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    public void setTaskStakeholders(org.drools.ws_ht.TOrganizationalEntity value) {
        this.taskStakeholders = value;
    }

    /**
     * Gets the value of the potentialOwners property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TOrganizationalEntity.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "POTENTIALOWNERS_TTASK_ID")
    public org.drools.ws_ht.TOrganizationalEntity getPotentialOwners() {
        return potentialOwners;
    }

    /**
     * Sets the value of the potentialOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    public void setPotentialOwners(org.drools.ws_ht.TOrganizationalEntity value) {
        this.potentialOwners = value;
    }

    /**
     * Gets the value of the businessAdministrators property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TOrganizationalEntity.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "BUSINESSADMINISTRATORS_TTASK_0")
    public org.drools.ws_ht.TOrganizationalEntity getBusinessAdministrators() {
        return businessAdministrators;
    }

    /**
     * Sets the value of the businessAdministrators property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    public void setBusinessAdministrators(org.drools.ws_ht.TOrganizationalEntity value) {
        this.businessAdministrators = value;
    }

    /**
     * Gets the value of the actualOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ACTUALOWNER")
    public String getActualOwner() {
        return actualOwner;
    }

    /**
     * Sets the value of the actualOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualOwner(String value) {
        this.actualOwner = value;
    }

    /**
     * Gets the value of the notificationRecipients property.
     * 
     * @return
     *     possible object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    @ManyToOne(targetEntity = org.drools.ws_ht.TOrganizationalEntity.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "NOTIFICATIONRECIPIENTS_TTASK_0")
    public org.drools.ws_ht.TOrganizationalEntity getNotificationRecipients() {
        return notificationRecipients;
    }

    /**
     * Sets the value of the notificationRecipients property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.drools.ws_ht.TOrganizationalEntity }
     *     
     */
    public void setNotificationRecipients(org.drools.ws_ht.TOrganizationalEntity value) {
        this.notificationRecipients = value;
    }

    /**
     * Gets the value of the createdOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getCreatedOn() {
        return createdOn;
    }

    /**
     * Sets the value of the createdOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedOn(XMLGregorianCalendar value) {
        this.createdOn = value;
    }

    /**
     * Gets the value of the createdBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CREATEDBY")
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * Sets the value of the createdBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatedBy(String value) {
        this.createdBy = value;
    }

    /**
     * Gets the value of the activationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getActivationTime() {
        return activationTime;
    }

    /**
     * Sets the value of the activationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivationTime(XMLGregorianCalendar value) {
        this.activationTime = value;
    }

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationTime(XMLGregorianCalendar value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the isSkipable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "ISSKIPABLE")
    public Boolean isIsSkipable() {
        return isSkipable;
    }

    /**
     * Sets the value of the isSkipable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSkipable(Boolean value) {
        this.isSkipable = value;
    }

    /**
     * Gets the value of the hasPotentialOwners property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "HASPOTENTIALOWNERS")
    public Boolean isHasPotentialOwners() {
        return hasPotentialOwners;
    }

    /**
     * Sets the value of the hasPotentialOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasPotentialOwners(Boolean value) {
        this.hasPotentialOwners = value;
    }

    /**
     * Gets the value of the startByExists property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "STARTBYEXISTS")
    public Boolean isStartByExists() {
        return startByExists;
    }

    /**
     * Sets the value of the startByExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStartByExists(Boolean value) {
        this.startByExists = value;
    }

    /**
     * Gets the value of the completeByExists property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "COMPLETEBYEXISTS")
    public Boolean isCompleteByExists() {
        return completeByExists;
    }

    /**
     * Sets the value of the completeByExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompleteByExists(Boolean value) {
        this.completeByExists = value;
    }

    /**
     * Gets the value of the presentationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRESENTATIONNAME", length = 64)
    public String getPresentationName() {
        return presentationName;
    }

    /**
     * Sets the value of the presentationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationName(String value) {
        this.presentationName = value;
    }

    /**
     * Gets the value of the presentationSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRESENTATIONSUBJECT", length = 254)
    public String getPresentationSubject() {
        return presentationSubject;
    }

    /**
     * Sets the value of the presentationSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentationSubject(String value) {
        this.presentationSubject = value;
    }

    /**
     * Gets the value of the renderingMethodExists property.
     * 
     */
    @Basic
    @Column(name = "RENDERINGMETHODEXISTS")
    public boolean isRenderingMethodExists() {
        return renderingMethodExists;
    }

    /**
     * Sets the value of the renderingMethodExists property.
     * 
     */
    public void setRenderingMethodExists(boolean value) {
        this.renderingMethodExists = value;
    }

    /**
     * Gets the value of the hasOutput property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "HASOUTPUT")
    public Boolean isHasOutput() {
        return hasOutput;
    }

    /**
     * Sets the value of the hasOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasOutput(Boolean value) {
        this.hasOutput = value;
    }

    /**
     * Gets the value of the hasFault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "HASFAULT")
    public Boolean isHasFault() {
        return hasFault;
    }

    /**
     * Sets the value of the hasFault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasFault(Boolean value) {
        this.hasFault = value;
    }

    /**
     * Gets the value of the hasAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "HASATTACHMENTS")
    public Boolean isHasAttachments() {
        return hasAttachments;
    }

    /**
     * Sets the value of the hasAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasAttachments(Boolean value) {
        this.hasAttachments = value;
    }

    /**
     * Gets the value of the hasComments property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "HASCOMMENTS")
    public Boolean isHasComments() {
        return hasComments;
    }

    /**
     * Sets the value of the hasComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasComments(Boolean value) {
        this.hasComments = value;
    }

    /**
     * Gets the value of the escalated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "ESCALATED")
    public Boolean isEscalated() {
        return escalated;
    }

    /**
     * Sets the value of the escalated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEscalated(Boolean value) {
        this.escalated = value;
    }

    /**
     * Gets the value of the primarySearchBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRIMARYSEARCHBY")
    public String getPrimarySearchBy() {
        return primarySearchBy;
    }

    /**
     * Sets the value of the primarySearchBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarySearchBy(String value) {
        this.primarySearchBy = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    @Transient
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * 
     * 
     */
    public void setAny(List<Object> any) {
        this.any = any;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @Basic
    @Column(name = "NAMEITEM")
    public String getNameItem() {
        return XmlAdapterUtils.unmarshall(QNameAsString.class, this.getName());
    }

    public void setNameItem(String target) {
        setName(XmlAdapterUtils.marshall(QNameAsString.class, target));
    }

    @Basic
    @Column(name = "CREATEDONITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getCreatedOnItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getCreatedOn());
    }

    public void setCreatedOnItem(Date target) {
        setCreatedOn(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    @Basic
    @Column(name = "ACTIVATIONTIMEITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getActivationTimeItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getActivationTime());
    }

    public void setActivationTimeItem(Date target) {
        setActivationTime(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    @Basic
    @Column(name = "EXPIRATIONTIMEITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getExpirationTimeItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getExpirationTime());
    }

    public void setExpirationTimeItem(Date target) {
        setExpirationTime(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    @OneToMany(targetEntity = org.drools.ws_ht.api.TTask.AnyItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ANYITEMS_TTASK_ID")
    public List<TTask.AnyItem> getAnyItems() {
        if (this.anyItems == null) {
            this.anyItems = new ArrayList<TTask.AnyItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.any)) {
            this.any = ItemUtils.wrap(this.any, this.anyItems, TTask.AnyItem.class);
        }
        return this.anyItems;
    }

    public void setAnyItems(List<TTask.AnyItem> value) {
        this.any = null;
        this.anyItems = null;
        this.anyItems = value;
        if (this.anyItems == null) {
            this.anyItems = new ArrayList<TTask.AnyItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.any)) {
            this.any = ItemUtils.wrap(this.any, this.anyItems, TTask.AnyItem.class);
        }
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TTask)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final TTask that = ((TTask) object);
        equalsBuilder.append(this.getId(), that.getId());
        equalsBuilder.append(this.getTaskType(), that.getTaskType());
        equalsBuilder.append(this.getName(), that.getName());
        equalsBuilder.append(this.getStatus(), that.getStatus());
        equalsBuilder.append(this.getPriority(), that.getPriority());
        equalsBuilder.append(this.getTaskInitiator(), that.getTaskInitiator());
        equalsBuilder.append(this.getTaskStakeholders(), that.getTaskStakeholders());
        equalsBuilder.append(this.getPotentialOwners(), that.getPotentialOwners());
        equalsBuilder.append(this.getBusinessAdministrators(), that.getBusinessAdministrators());
        equalsBuilder.append(this.getActualOwner(), that.getActualOwner());
        equalsBuilder.append(this.getNotificationRecipients(), that.getNotificationRecipients());
        equalsBuilder.append(this.getCreatedOn(), that.getCreatedOn());
        equalsBuilder.append(this.getCreatedBy(), that.getCreatedBy());
        equalsBuilder.append(this.getActivationTime(), that.getActivationTime());
        equalsBuilder.append(this.getExpirationTime(), that.getExpirationTime());
        equalsBuilder.append(this.isIsSkipable(), that.isIsSkipable());
        equalsBuilder.append(this.isHasPotentialOwners(), that.isHasPotentialOwners());
        equalsBuilder.append(this.isStartByExists(), that.isStartByExists());
        equalsBuilder.append(this.isCompleteByExists(), that.isCompleteByExists());
        equalsBuilder.append(this.getPresentationName(), that.getPresentationName());
        equalsBuilder.append(this.getPresentationSubject(), that.getPresentationSubject());
        equalsBuilder.append(this.isRenderingMethodExists(), that.isRenderingMethodExists());
        equalsBuilder.append(this.isHasOutput(), that.isHasOutput());
        equalsBuilder.append(this.isHasFault(), that.isHasFault());
        equalsBuilder.append(this.isHasAttachments(), that.isHasAttachments());
        equalsBuilder.append(this.isHasComments(), that.isHasComments());
        equalsBuilder.append(this.isEscalated(), that.isEscalated());
        equalsBuilder.append(this.getPrimarySearchBy(), that.getPrimarySearchBy());
        equalsBuilder.append(this.getAny(), that.getAny());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TTask)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getId());
        hashCodeBuilder.append(this.getTaskType());
        hashCodeBuilder.append(this.getName());
        hashCodeBuilder.append(this.getStatus());
        hashCodeBuilder.append(this.getPriority());
        hashCodeBuilder.append(this.getTaskInitiator());
        hashCodeBuilder.append(this.getTaskStakeholders());
        hashCodeBuilder.append(this.getPotentialOwners());
        hashCodeBuilder.append(this.getBusinessAdministrators());
        hashCodeBuilder.append(this.getActualOwner());
        hashCodeBuilder.append(this.getNotificationRecipients());
        hashCodeBuilder.append(this.getCreatedOn());
        hashCodeBuilder.append(this.getCreatedBy());
        hashCodeBuilder.append(this.getActivationTime());
        hashCodeBuilder.append(this.getExpirationTime());
        hashCodeBuilder.append(this.isIsSkipable());
        hashCodeBuilder.append(this.isHasPotentialOwners());
        hashCodeBuilder.append(this.isStartByExists());
        hashCodeBuilder.append(this.isCompleteByExists());
        hashCodeBuilder.append(this.getPresentationName());
        hashCodeBuilder.append(this.getPresentationSubject());
        hashCodeBuilder.append(this.isRenderingMethodExists());
        hashCodeBuilder.append(this.isHasOutput());
        hashCodeBuilder.append(this.isHasFault());
        hashCodeBuilder.append(this.isHasAttachments());
        hashCodeBuilder.append(this.isHasComments());
        hashCodeBuilder.append(this.isEscalated());
        hashCodeBuilder.append(this.getPrimarySearchBy());
        hashCodeBuilder.append(this.getAny());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @Entity(name = "org.drools.ws_ht.api.TTask$AnyItem")
    @Table(name = "TTASKANYITEM")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class AnyItem
        implements Item<Object> , Equals, HashCode
    {

        @XmlAnyElement(lax = true)
        protected Object item;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * 
         * 
         * @return
         *     possible object is
         *     {@link Element }
         *     {@link Object }
         *     
         */
        @Transient
        public Object getItem() {
            return item;
        }

        /**
         * 
         * 
         * @param value
         *     allowed object is
         *     {@link Element }
         *     {@link Object }
         *     
         */
        public void setItem(Object value) {
            this.item = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        @Basic
        @Column(name = "ITEMELEMENT")
        @Lob
        public String getItemElement() {
            if (this.getItem() instanceof Element) {
                return XmlAdapterUtils.unmarshall(ElementAsString.class, ((Element) this.getItem()));
            } else {
                return null;
            }
        }

        public void setItemElement(String target) {
            if (target!= null) {
                setItem(XmlAdapterUtils.marshall(ElementAsString.class, target));
            }
        }

        @Basic
        @Column(name = "ITEMOBJECT")
        @Lob
        public String getItemObject() {
            if (JAXBContextUtils.isElement("org.drools.ws_ht:org.drools.ws_ht.api.xsd:org.drools.ws_ht.api", this.getItem())) {
                return JAXBContextUtils.unmarshall("org.drools.ws_ht:org.drools.ws_ht.api.xsd:org.drools.ws_ht.api", this.getItem());
            } else {
                return null;
            }
        }

        public void setItemObject(String target) {
            if (target!= null) {
                setItem(JAXBContextUtils.marshall("org.drools.ws_ht:org.drools.ws_ht.api.xsd:org.drools.ws_ht.api", target));
            }
        }

        public void equals(Object object, EqualsBuilder equalsBuilder) {
            if (!(object instanceof TTask.AnyItem)) {
                equalsBuilder.appendSuper(false);
                return ;
            }
            if (this == object) {
                return ;
            }
            final TTask.AnyItem that = ((TTask.AnyItem) object);
            equalsBuilder.append(this.getItem(), that.getItem());
        }

        public boolean equals(Object object) {
            if (!(object instanceof TTask.AnyItem)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
            equals(object, equalsBuilder);
            return equalsBuilder.isEquals();
        }

        public void hashCode(HashCodeBuilder hashCodeBuilder) {
            hashCodeBuilder.append(this.getItem());
        }

        public int hashCode() {
            final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
            hashCode(hashCodeBuilder);
            return hashCodeBuilder.toHashCode();
        }

    }

}
